# Generated by Django 4.2.11 on 2024-04-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=170, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(max_length=170, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('ie', models.CharField(max_length=9, verbose_name='Inscrição estadual')),
                ('telefone_fixo', models.CharField(max_length=10, verbose_name='Telefone fixo')),
                ('telefone_movel', models.CharField(max_length=12, verbose_name='Telefone movél')),
                ('observacao', models.CharField(max_length=255, verbose_name='Observação')),
            ],
        ),
    ]
