# Generated by Django 4.2.11 on 2024-04-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefone_fixo',
            field=models.CharField(max_length=10, null=True, verbose_name='Telefone fixo'),
        ),
    ]
