# Generated by Django 4.2.11 on 2024-03-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('estoque', models.IntegerField(verbose_name='Estoque')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço de custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço de venda')),
                ('embalagem', models.CharField(choices=[('caixa', 'Caixa'), ('duzia', 'Duzia'), ('unidade', 'Unidade'), ('kilo', 'Kilo'), ('peca', 'Peça'), ('embalagem', 'Embalagem'), ('metro', 'Metro'), ('outros', 'Outros')], max_length=35, verbose_name='Embalagem')),
            ],
        ),
    ]
