# Generated by Django 4.2.11 on 2024-04-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresas', '0003_alter_empresa_observacao_alter_empresa_telefone_fixo'),
        ('app_usuarios', '0004_customuser_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresas.empresa', verbose_name='Empresa'),
        ),
    ]
