# Generated by Django 4.2.11 on 2024-04-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0002_alter_cliente_cep_alter_cliente_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone fixo'),
        ),
    ]
