# Generated by Django 4.2.11 on 2024-04-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0003_alter_cliente_cnpj_alter_cliente_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone fixo'),
        ),
    ]
